src/java/com/etranzact/corporatepay/payment/web/BeneficiaryGroupBean.java
package com.etranzact.corporatepay.payment.web;

import com.etranzact.corporatepay.core.web.AbstractBean;
import com.etranzact.corporatepay.model.Beneficiary;
import com.etranzact.corporatepay.model.BeneficiaryGroup;
import com.etranzact.corporatepay.setup.facade.BeneficiaryFacadeLocal;
import com.etranzact.corporatepay.setup.facade.BeneficiaryGroupFacadeLocal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import org.primefaces.event.SelectEvent;

@ManagedBean(name = "beneficiaryGroupBean")
@SessionScoped
public class BeneficiaryGroupBean extends AbstractBean<BeneficiaryGroup> {

    @EJB
    private BeneficiaryFacadeLocal beneficiaryFacadeLocal;

    @EJB
    private BeneficiaryGroupFacadeLocal beneficiaryGroupFacadeLocal;

    private List<BeneficiaryGroup> beneficiaryGroups;
        private List<Beneficiary> beneficiarys;
           private Beneficiary beneficiary;

    @Override
    protected BeneficiaryGroupFacadeLocal getFacade() {
        return this.beneficiaryGroupFacadeLocal;
    }

    public BeneficiaryGroupBean() {
        super(BeneficiaryGroup.class);
    }
    
    public void addBeneficiary() {
             FacesMessage m = new FacesMessage();
        try {
            beneficiary.setBeneficiaryGroup(selectedItem);
                      beneficiaryFacadeLocal.save(beneficiary);
                      beneficiary = null;
            m.setSeverity(FacesMessage.SEVERITY_INFO);
            m.setSummary("Beneficiary Add to Group");
            FacesContext.getCurrentInstance().addMessage(null, m);
        } catch (Exception ex) {
            Logger.getLogger(BeneficiaryGroupBean.class.getName()).log(Level.SEVERE, null, ex);
            m.setSeverity(FacesMessage.SEVERITY_ERROR);
            m.setSummary(ex.getMessage());
            FacesContext.getCurrentInstance().addMessage(null, m);
        }   
    }
    
        public void removeBeneficiaryFromGroup() {
             FacesMessage m = new FacesMessage();
        try {
            beneficiary.setBeneficiaryGroup(null);
             beneficiaryFacadeLocal.save(beneficiary);
             beneficiary= null;
            m.setSeverity(FacesMessage.SEVERITY_INFO);
            m.setSummary("Beneficiary Removed to Group");
            FacesContext.getCurrentInstance().addMessage(null, m);
        } catch (Exception ex) {
            Logger.getLogger(BeneficiaryGroupBean.class.getName()).log(Level.SEVERE, null, ex);
            m.setSeverity(FacesMessage.SEVERITY_ERROR);
            m.setSummary(ex.getMessage());
            FacesContext.getCurrentInstance().addMessage(null, m);
        }   
    }
    
    @Override
        public void onRowSelect(SelectEvent selectEvent) {
        try {
            super.onRowSelect(selectEvent);
            Map<String,Object> m = new HashMap();
            m.put("beneficiaryGroup", selectedItem);
            beneficiarys= beneficiaryFacadeLocal.findAll(m, false);
        } catch (Exception ex) {
            Logger.getLogger(BeneficiaryGroupBean.class.getName()).log(Level.SEVERE, null, ex);
                FacesMessage m = new FacesMessage();
                       m.setSeverity(FacesMessage.SEVERITY_ERROR);
            m.setSummary("Error Retrieving Beneficiaries");
            FacesContext.getCurrentInstance().addMessage(null, m);
        }
    }

    public void createBenGroup() {
        FacesMessage m = new FacesMessage();
        try {
            selectedItem.setCorporate(getLoggedCorporate());
            selectedItem.setCreator(getLoggedUser().getId());
            getFacade().create(selectedItem);
            m.setSeverity(FacesMessage.SEVERITY_INFO);
            m.setSummary("Beneficiary Group Created");
            FacesContext.getCurrentInstance().addMessage(null, m);
        } catch (Exception ex) {
            Logger.getLogger(BeneficiaryGroupBean.class.getName()).log(Level.SEVERE, null, ex);
            m.setSeverity(FacesMessage.SEVERITY_ERROR);
            m.setSummary(ex.getMessage());
            FacesContext.getCurrentInstance().addMessage(null, m);
        }
    }

    /**
     * @return the beneficiaryGroups
     */
    public List<BeneficiaryGroup> getBeneficiaryGroups() {
        try {
            Map<String, Object> m = new HashMap<>();
            m.put("corporate", getLoggedCorporate());
            beneficiaryGroups = getFacade().findAll(m, true);
            return beneficiaryGroups;
        } catch (Exception ex) {
            Logger.getLogger(BeneficiaryGroupBean.class.getName()).log(Level.SEVERE, null, ex);
            return new ArrayList<>();
        }
    }

    /**
     * @param beneficiaryGroups the beneficiaryGroups to set
     */
    public void setBeneficiaryGroups(List<BeneficiaryGroup> beneficiaryGroups) {
        this.beneficiaryGroups = beneficiaryGroups;
    }

    /**
     * @return the beneficiarys
     */
    public List<Beneficiary> getBeneficiarys() {
        return beneficiarys;
    }

    /**
     * @param beneficiarys the beneficiarys to set
     */
    public void setBeneficiarys(List<Beneficiary> beneficiarys) {
        this.beneficiarys = beneficiarys;
    }

    /**
     * @return the beneficiary
     */
    public Beneficiary getBeneficiary() {
        return beneficiary;
    }

    /**
     * @param beneficiary the beneficiary to set
     */
    public void setBeneficiary(Beneficiary beneficiary) {
        this.beneficiary = beneficiary;
    }

    
    
}

src/java/com/etranzact/corporatepay/payment/web/TransactionReversalTableBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.etranzact.corporatepay.payment.web;

import com.etranzact.corporatepay.core.web.*;
import com.etranzact.corporatepay.model.Bank;
import com.etranzact.corporatepay.model.Corporate;
import com.etranzact.corporatepay.model.Payment;
import com.etranzact.corporatepay.model.Transaction;
import com.etranzact.corporatepay.model.dto.SettlementDto;
import com.etranzact.corporatepay.payment.facade.TransactionFacadeLocal;
import com.etranzact.corporatepay.setup.facade.BankSetupFacadeLocal;
import com.etranzact.corporatepay.setup.facade.CorporateSetupFacadeLocal;
import com.etranzact.corporatepay.util.AppConstants;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.model.SelectItem;

/**
 *
 * @author oluwasegun.idowu
 */
@ManagedBean(name = "transactionReversalTableBean")
@SessionScoped
public class TransactionReversalTableBean extends TransactionTableBean {

     @Override
     public String getStatusFilter() {
          return AppConstants.TRANSACTION_REVERSED;
     }

      @PostConstruct
    @Override
    public void init() {
        dateField = "revDate";
        reportPage=true;
        prefetch = false;
        super.init();
    }
    
    
   

}

src/java/com/etranzact/corporatepay/payment/web/TransactionTableBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.etranzact.corporatepay.payment.web;

import com.etranzact.corporatepay.core.web.*;
import com.etranzact.corporatepay.model.Bank;
import com.etranzact.corporatepay.model.Corporate;
import com.etranzact.corporatepay.model.Transaction;
import com.etranzact.corporatepay.payment.facade.TransactionFacadeLocal;
import com.etranzact.corporatepay.setup.facade.BankSetupFacadeLocal;
import com.etranzact.corporatepay.setup.facade.CorporateSetupFacadeLocal;
import com.etranzact.corporatepay.util.AppConstants;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.model.SelectItem;

/**
 *
 * @author oluwasegun.idowu
 */
@ManagedBean(name = "transactionTableBean")
@SessionScoped
public class TransactionTableBean extends AbstractTableBean<Transaction> {

    @EJB
    protected TransactionFacadeLocal transactionFacadeLocal;
    protected String paymentRefFilter = "";
    protected String transactionRefFilter = "";
    protected String narration = "";
    protected String accountNumber = "";
    protected String accountName = "";
    protected BigDecimal amount;
    protected Bank srcBankFilter;
    protected Corporate corporateFilter;
    protected String statusFilter2 = "";
    protected List<Bank> banks;
    protected List<Corporate> corporates;

    @EJB
    protected CorporateSetupFacadeLocal corporateFacadeLocal;
    @EJB
    protected BankSetupFacadeLocal bankFacadeLocal;

    public TransactionTableBean() {
        super(Transaction.class);
    }

    @Override
    protected TransactionFacadeLocal getFacade() {
        return transactionFacadeLocal; //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    protected TableProperties getTableProperties() {
        TableProperties properties = new TableProperties();
        if (!paymentRefFilter.isEmpty()) {
            paymentRefFilter = paymentRefFilter.startsWith("08")?paymentRefFilter.substring(2):paymentRefFilter;
            properties.getAdditionalFilter().put("payment.id=" + paymentRefFilter, null);
        }
        if (!transactionRefFilter.isEmpty()) {
            String filter = "";
            String[] split = transactionRefFilter.split(",");
            for(String str: split) {
               str = str.startsWith("08")?str.substring(2):str;
               filter +=str + ",";
            }
            filter = filter.substring(0, filter.length()-1);
            properties.getAdditionalFilter().put("transactionId in (" + filter + ")", null);
        }
        if (!narration.isEmpty()) {
            properties.getAdditionalFilter().put("narration", getNarration());
        }
        if (getAmount() != null) {
            properties.getAdditionalFilter().put("amount", getAmount());
        }
        if (!accountNumber.isEmpty()) {
            properties.getAdditionalFilter().put("account.accountNumber", getAccountNumber());
        }
        if (!accountName.isEmpty()) {
            properties.getAdditionalFilter().put("account.accountName", getAccountName());
        }
        if (getStatusFilter() != null && !getStatusFilter().isEmpty()) {
            if (getStatusFilter().equals("3")) {
                properties.getAdditionalFilter().put("transactionStatus in (3,7,8,9)", null);
            } else {
                properties.getAdditionalFilter().put("transactionStatus", getStatusFilter());
            }
        } else {
            properties.getAdditionalFilter().put("transactionStatus in (3,4,5,6,7,8,9)", null);
        }
//           if (!statusFilter2.isEmpty()) {
//            properties.getAdditionalFilter().put("transactionStatus", getStatusFilter2());
//        }
        Bank bank = getLoggedBank();
        if (srcBankFilter != null) {
            bank = srcBankFilter;
        }
        Corporate corporate = getLoggedCorporate();
        if (corporateFilter != null) {
            corporate = corporateFilter;
        }
        if (bank != null && corporate == null) {
            properties.getAdditionalFilter().put("corporate.bank", bank);
        }
        if (corporate != null) {
            properties.getAdditionalFilter().put("corporate", corporate);
        }
        properties.getAdditionalFilter().put("t.schedule is null", null);
        properties.setFlagStatuses(new String[0]);
        return properties;
    }

    @PostConstruct
    @Override
    public void init() {
        dateField = "dateCreated";        
        prefetch = !reportPage;
        super.init();
    }

    @Override
    public void refresh() {
        prefetch = true;
        super.init();
    }

    @Override
    public Transaction getTableRowData(String rowKey) {
        List<Transaction> wrappedData = (List<Transaction>) getLazyDataModel().getWrappedData();
        for (Transaction t : wrappedData) {
            if (rowKey.equals(t.getTransactionId().toString())) {
                return t;
            }
        }
        return null;
    }

    @Override
    public List<SelectItem> getStatusOptions() {
        List<SelectItem> options = new ArrayList<>();
        options.add(new SelectItem(AppConstants.TRANSACTION_PENDING_PAYMENT, AppConstants.TRANSACTION_PENDING_PAYMENT_TEXT));
        options.add(new SelectItem(AppConstants.TRANSACTION_PAID, AppConstants.TRANSACTION_PAID_TEXT));
        options.add(new SelectItem(AppConstants.TRANSACTION_FAILED, AppConstants.TRANSACTION_FAILED_TEXT));
        options.add(new SelectItem(AppConstants.TRANSACTION_STATUS_UNKNOWN, AppConstants.TRANSACTION_STATUSUNKNOWN_TEXT));
        options.add(new SelectItem(AppConstants.TRANSACTION_REVERSED, AppConstants.TRANSACTION_REVERSED_TEXT));
        return options;
    }

    public List<SelectItem> getStatusOptions2() {
        List<SelectItem> options = new ArrayList<>();
        options.add(new SelectItem(AppConstants.TRANSACTION_CREATED_OK, AppConstants.TRANSACTION_CREATED_OK_TEXT));
        options.add(new SelectItem(AppConstants.TRANSACTION_PENDING_APPROVAL, AppConstants.TRANSACTION_PENDING_APPROVAL_TEXT));
        return options;
    }

    @Override
    public Object getTableKey(Transaction t) {
        return t.getTransactionId(); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * @return the paymentRefFilter
     */
    public String getPaymentRefFilter() {
        return paymentRefFilter;
    }

    /**
     * @param paymentRefFilter the paymentRefFilter to set
     */
    public void setPaymentRefFilter(String paymentRefFilter) {
        this.paymentRefFilter = paymentRefFilter;
    }

    /**
     * @return the transactionRefFilter
     */
    public String getTransactionRefFilter() {
        return transactionRefFilter;
    }

    /**
     * @param transactionRefFilter the transactionRefFilter to set
     */
    public void setTransactionRefFilter(String transactionRefFilter) {
        this.transactionRefFilter = transactionRefFilter;
    }

    /**
     * @return the narration
     */
    public String getNarration() {
        return narration;
    }

    /**
     * @param narration the narration to set
     */
    public void setNarration(String narration) {
        this.narration = narration;
    }

    /**
     * @return the accountNumber
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * @param accountNumber the accountNumber to set
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * @return the accountName
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * @param accountName the accountName to set
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * @return the amount
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * @param amount the amount to set
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * @return the srcBankFilter
     */
    public Bank getSrcBankFilter() {
        return srcBankFilter;
    }

    /**
     * @param srcBankFilter the srcBankFilter to set
     */
    public void setSrcBankFilter(Bank srcBankFilter) {
        this.srcBankFilter = srcBankFilter;
    }

    /**
     * @return the corporateFilter
     */
    public Corporate getCorporateFilter() {
        return corporateFilter;
    }

    /**
     * @param corporateFilter the corporateFilter to set
     */
    public void setCorporateFilter(Corporate corporateFilter) {
        this.corporateFilter = corporateFilter;
    }

    /**
     * @return the banks
     */
    public List<Bank> getBanks() {
        if (banks == null) {

            try {
                banks = bankFacadeLocal.findAll(new HashMap(), true, "bankName");
                corporateFilter = null;
            } catch (Exception ex) {
                Logger.getLogger(UserBean.class.getName()).log(Level.SEVERE, null, ex);
                banks = new ArrayList<>();
            }
        }
        return banks;
    }

    /**
     * @param banks the banks to set
     */
    public void setBanks(List<Bank> banks) {
        this.banks = banks;
    }

    /**

web/WEB-INF/payment/report/transactiontable.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:fn="http://java.sun.com/jsp/jstl/functions"
                xmlns:p="http://primefaces.org/ui">
    <div class="Container100 Responsive">
        <div class="ContainerIndent"> 
            <h:form id="paymentTableRef">
                <p:panel  id="filter" header="Filter" toggleable="true" collapsed="false" widgetVar="filter">
                    <h:panelGrid id="paymentfilter" class="Container100" columns="6" cellpadding="1" cellspacing="10"> 
                        <p:outputLabel for="bankfilter" rendered="#{empty userBean.supportBank}" value="Initiating Bank" />
                        <p:selectOneMenu id="bankfilter" filter="true" filterMatchMode="startsWith"  rendered="#{empty userBean.supportBank}" style="width:200px" value="#{transactionReportTableBean.srcBankFilter}"  converter="bankConverter" >
                            <p:ajax event="change" update="corporatefilter"/> 
                            <f:selectItem itemLabel="--Select Bank--" itemValue="" />  
                            <f:selectItems value="#{transactionReportTableBean.banks}" var="bank" itemLabel="#{bank.bankName}" itemValue="#{bank}"  />  
                        </p:selectOneMenu>
                        <p:outputLabel for="corporatefilter" rendered="#{empty userBean.supportCorporate}" value="Initiating Corporate:" />
                        <p:selectOneMenu id="corporatefilter" filter="true" filterMatchMode="startsWith"   rendered="#{empty userBean.supportCorporate}"  style="width:200px" value="#{transactionReportTableBean.corporateFilter}"  converter="corporateConverter" >
                            <f:selectItem itemLabel="--Select Corporates--" itemValue="" />   
                            <f:selectItems value="#{transactionReportTableBean.corporates}" var="corporate" itemLabel="#{corporate.corporateName}" itemValue="#{corporate}"  />  
                        </p:selectOneMenu>
                        <p:outputLabel for="paymentRef" value="Payment Reference:" />
                        <p:inputText id="paymentRef" title="Payment Reference" value="${transactionReportTableBean.paymentRefFilter}" placeholder="Payment Reference"/>
                        <p:outputLabel for="transRef" value="Transaction Reference:" />
                        <p:inputText id="transRef" title="Transaction Reference" value="${transactionReportTableBean.transactionRefFilter}" placeholder="Transaction Reference"/>
                        <p:outputLabel for="narration" value="Narration:" />
                        <p:inputText id="narration" title="Narration" value="${transactionReportTableBean.narration}" placeholder="Narration"/>
                        <p:outputLabel for="accountNo" value="Account Number" />
                        <p:inputText id="accountNo" title="account Number" value="${transactionReportTableBean.accountNumber}" placeholder="Amount Number"/>
                        <p:outputLabel for="accountName" value="Account Number:" />
                        <p:inputText id="accountName" title="Account Name" value="${transactionReportTableBean.accountName}" placeholder="Amount Name"/>
                        <p:outputLabel for="amount" value="Amount:" />
                        <p:inputText id="amount" title="Amount" value="${transactionReportTableBean.amount}" placeholder="Amount"/>
                        <p:outputLabel for="fromDate"  value="From Date:" />
                        <p:calendar id="fromDate" value="#{transactionReportTableBean.fromDateFilter}" required="true" />
                        <p:outputLabel for="toDate"  value="To Date:" />
                        <p:calendar id="toDate" value="#{transactionReportTableBean.toDateFilter}" required="true" />	
                        <p:outputLabel for="statusfilter"   value="Filter Transactions:" />
                        <p:selectOneMenu id="statusfilter" style="width:200px"  value="#{transactionReportTableBean.statusFilter}" >
                            <f:selectItem itemLabel="--Select Status--" itemValue="" />  
                            <f:selectItems value="#{transactionReportTableBean.statusOptions}" var="statusvar" itemLabel="#{statusvar}" itemValue="#{statusvar}"  />  
                        </p:selectOneMenu> 
                        <p:outputLabel/>
                        <p:outputLabel/>
                        <p:commandButton value="Get Report" onstart="showProgress()" oncomplete="hideProgress()" update=":paymentTableRef" action="#{transactionReportTableBean.refresh}" styleClass="GreenButton Fleft" />
                    </h:panelGrid>
                </p:panel>
                <p:dataTable id="transactionTable" lazy="true" var="transaction" class="Container100_"
                             value="${transactionReportTableBean.lazyDataModel}" paginator="true" sortField="transactionId" sortOrder="descending" 
                             rows="${transactionReportTableBean.rowcount}"  selectionMode="single" selection="#{transactionBean.selectedItem}" 
                             paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                             rowsPerPageTemplate="5,10,15">
                    <f:facet name="header"> 
                        <div align="center">
                            Transactions
                        </div>
                        <div align="left">
                            <p:commandLink  ajax="false" update=":paymentTableRef:transactionTable" rendered="${not empty transactionReportTableBean.allList}"  action="#{reportBean.generateTransReport('pdfTransRep')}"  title="PDF Download">
                                <h:graphicImage name="images/pdf.png" width="32px" height="32px"  styleClass="Fleft" library="sentinel-layout"/>
                            </p:commandLink>
                            <p:commandLink  ajax="false" update=":paymentTableRef:transactionTable" rendered="${not empty transactionReportTableBean.allList}"  action="#{reportBean.generateTransReport('excelTransRep')}"  title="Excel Download with Graphics">
                                <h:graphicImage name="images/excel.jpg" width="32px" height="32px"  styleClass="Fleft" library="sentinel-layout"/>
                            </p:commandLink>
                            <p:commandLink  ajax="false" update=":paymentTableRef:transactionTable" rendered="${not empty transactionReportTableBean.allList}"  action="#{reportBean.generateTransReport('excelTransRep2')}"  title="Plain Excel Download">
                                <h:graphicImage name="images/excel.png" width="32px" height="32px"  styleClass="Fleft" library="sentinel-layout"/>
                            </p:commandLink>
                        </div>  
                    </f:facet>
                    <p:ajax event="rowSelect" listener="#{transactionBean.onRowSelect}" onstart="showProgress()" oncomplete="hideProgress()" />
                    <p:column headerText="" style="width: 35px">
                        <p:commandLink  ajax="false" rendered="#{transaction.trsnsactionStatus eq '4'}" action="#{reportBean.generateTransReceipt(transaction)}" title="Transaction Receipt">
                            <h:graphicImage name="images/pdf.png" width="24px" height="24px"  styleClass="Fleft" library="sentinel-layout"/>
                        </p:commandLink>
                    </p:column>
                    <p:column headerText="Initiating Corporate" style="width: 80px" ><h:outputText value="#{transaction.corporate.corporateName}" /></p:column>
                    <p:column headerText="Initiating Bank" style="width: 80px" ><h:outputText value="#{transaction.corporate.bank.bankName}" /></p:column>
                    <p:column headerText="Payment Reference" style="width: 80px" ><h:outputText value="08#{transaction.payment.paymentReference}" /></p:column>
                    <p:column headerText="Transaction Reference" style="width: 140px"><h:outputText value="08#{transaction.transactionReference}" /></p:column>
                    <p:column headerText="Beneficiary Bank" style="width: 80px"><h:outputText value="#{transaction.beneficiary.account.bankName}" /></p:column>
                    <p:column headerText="Beneficiary Name" style="width: 80px"><h:outputText value="#{transaction.beneficiary.beneficiaryName}" /></p:column>
                    <p:column headerText="Beneficiary Account" style="width: 80px"><h:outputText value="#{transaction.beneficiary.account.accountNumber}" /></p:column>
                     <p:column headerText="Holding Account" rendered="#{userBean.bankUser or userBean.etzUser}"  style="width: 80px"><h:outputText value="#{transaction.payment.holdingAccount.cardNumber}" /></p:column>
                     <p:column headerText="Initiating Card Number" style="width: 80px"><h:outputText value="#{transaction.payment.card.cardNumber}" /></p:column>
                    <p:column headerText="Narration" style="width: 180px"><h:outputText value="#{transaction.narration}" /></p:column>
                    <p:column headerText="Amount(NGN)" style="width: 85px"><h:outputText value="#{transaction.amountf}" /></p:column>
                    <p:column headerText="Commission(NGN)" rendered="#{userBean.etzUser}" style="width: 85px"><h:outputText value="#{transaction.etzFeeAmount}" /></p:column>
                    <p:column headerText="Bank Commission(NGN)" rendered="#{userBean.bankUser or userBean.etzUser}" style="width: 85px"><h:outputText value="#{transaction.bankFeeAmount}" /></p:column>
                    <p:column headerText="ThirdParty Commission(NGN)" rendered="#{userBean.bankUser or userBean.etzUser}" style="width: 85px"><h:outputText value="#{transaction.thirdpartyFeeAmount}" /></p:column>
                    <p:column headerText="ThirdParty2 Commission(NGN)" rendered="#{userBean.bankUser or userBean.etzUser}" style="width: 85px"><h:outputText value="#{transaction.thirdpartyFeeAmount2}" /></p:column>
                    <p:column headerText="S BatchID" style="width: 150px" rendered="#{userBean.etzUser}"><h:outputText value="#{transaction.sbatchId}" /></p:column>
                    <p:column headerText="Authorized Date" style="width: 100px" ><h:outputText value="#{transaction.payment.authorizedDateStr}" /></p:column>
                    <p:column headerText="Authorized By" style="width:100px" ><h:outputText value="#{transaction.payment.authorizedBy}" /></p:column>
                    <p:column headerText="Failed Response" rendered="#{transactionBean.etzUser}" style="width: 85px"><h:outputText value="#{not empty transaction.responseCode and transaction.responseCode ne '0' and transaction.responseCode ne '00' and transaction.responseCode ne '000'?'':transaction.responseCode}" /></p:column>
                    <p:column headerText="Status" style="width: 70px"><h:outputText value="#{transaction.status}" /></p:column>
                </p:dataTable>

            </h:form>
        </div></div>
</ui:composition>